name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Linting (Flake8)
      run: |
        pip install flake8
        flake8 . --count --max-line-length=127 --statistics
        continue-on-error: true 

    - name: Run Unit Tests
      run: |
        pytest test.py  # Assuming you're using pytest for unit tests

    - name: Test API Endpoints
      run: |
        pip install requests
        python test_api.py  # Add API endpoint tests in test_api.py if required

    - name: Static Code Analysis (e.g., Bandit for security)
      run: |
        pip install bandit
        bandit -r .
